import 'server-only';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

// Approved static template — contractual terms (salary, dates, benefits) are
// always populated from the offers row, never generated by AI, per the
// project rule that AI must not invent legal/contractual content.
export type OfferLetterData = {
  candidateName: string;
  jobTitle: string;
  department: string | null;
  salary: number;
  employmentType: string;
  joiningDate: string | null;
  benefits: string | null;
  acceptanceDeadline: string | null;
  companyName: string;
};

function formatDate(value: string | null) {
  if (!value) return 'To be confirmed';
  return new Date(value).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

export async function generateOfferLetterPdf(data: OfferLetterData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // US Letter
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const margin = 60;
  let y = 792 - margin;
  const lineHeight = 18;

  const drawText = (text: string, options: { bold?: boolean; size?: number; gap?: number } = {}) => {
    const usedFont = options.bold ? bold : font;
    const size = options.size ?? 11;
    const lines = wrapText(text, usedFont, size, 612 - margin * 2);
    for (const line of lines) {
      page.drawText(line, { x: margin, y, size, font: usedFont, color: rgb(0.1, 0.1, 0.1) });
      y -= lineHeight;
    }
    y -= options.gap ?? 6;
  };

  function wrapText(text: string, f: typeof font, size: number, maxWidth: number): string[] {
    const words = text.split(' ');
    const lines: string[] = [];
    let current = '';
    for (const word of words) {
      const candidate = current ? `${current} ${word}` : word;
      if (f.widthOfTextAtSize(candidate, size) > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = candidate;
      }
    }
    if (current) lines.push(current);
    return lines;
  }

  drawText(data.companyName, { bold: true, size: 16, gap: 20 });
  drawText(`Date: ${formatDate(new Date().toISOString())}`, { gap: 20 });

  drawText(`Dear ${data.candidateName},`, { gap: 14 });

  drawText(
    `We are pleased to offer you the position of ${data.jobTitle}${data.department ? ` in the ${data.department} department` : ''} at ${data.companyName}. This letter outlines the terms of your offer.`,
    { gap: 14 }
  );

  drawText('Position Details', { bold: true, size: 13, gap: 10 });
  drawText(`Job Title: ${data.jobTitle}`);
  drawText(`Employment Type: ${data.employmentType.replace('_', ' ')}`);
  drawText(`Annual Salary: ${data.salary.toLocaleString('en-US', { style: 'currency', currency: 'USD' })}`);
  drawText(`Joining Date: ${formatDate(data.joiningDate)}`);
  if (data.benefits) drawText(`Benefits: ${data.benefits}`);
  y -= 8;

  drawText(
    `This offer is contingent upon your acceptance by ${formatDate(data.acceptanceDeadline)}. Please sign and return this letter to confirm your acceptance.`,
    { gap: 20 }
  );

  drawText('We look forward to welcoming you to the team.', { gap: 30 });

  drawText('Sincerely,', { gap: 40 });
  drawText(`${data.companyName} — Human Resources`, { bold: true });

  y -= 30;
  page.drawText('Candidate Signature: ______________________________', { x: margin, y, size: 11, font });
  y -= lineHeight * 2;
  page.drawText('Date: ______________________________', { x: margin, y, size: 11, font });

  return doc.save();
}
