import { z } from 'zod';

export const JobDescriptionSchema = z.object({
  description: z.string(),
  responsibilities: z.string(),
  required_qualifications: z.array(z.string()),
  preferred_qualifications: z.array(z.string()),
  required_skills: z.array(z.string()),
  preferred_skills: z.array(z.string()),
  screening_criteria: z.array(z.string()),
  interview_criteria: z.array(z.string()),
});
export type JobDescriptionResult = z.infer<typeof JobDescriptionSchema>;

// Component signals only — no overall/final score. The final score is always
// computed deterministically in lib/scoring/weighted-score.ts, never by the LLM.
export const ResumeAnalysisSchema = z.object({
  skills_score: z.number().min(0).max(100),
  experience_score: z.number().min(0).max(100),
  technical_score: z.number().min(0).max(100),
  education_score: z.number().min(0).max(100),
  portfolio_score: z.number().min(0).max(100),
  matched_skills: z.array(z.string()),
  missing_skills: z.array(z.string()),
  strengths: z.array(z.string()),
  concerns: z.array(z.string()),
  summary: z.string(),
  recommendation: z.enum(['shortlist', 'hr_review', 'hold', 'reject']),
});
export type ResumeAnalysisResult = z.infer<typeof ResumeAnalysisSchema>;

// Deterministic fields (name/email/phone) are trusted from the application
// form itself, not re-derived by AI. This schema only covers fields that
// genuinely require reading unstructured resume text.
export const ResumeExtractionSchema = z.object({
  education: z.string().nullable(),
  years_experience: z.number().min(0).max(60).nullable(),
  previous_companies: z.array(z.string()),
  previous_roles: z.array(z.string()),
  technical_skills: z.array(z.string()),
  soft_skills: z.array(z.string()),
  certifications: z.array(z.string()),
  projects: z.array(z.object({ name: z.string(), description: z.string() })),
});
export type ResumeExtractionResult = z.infer<typeof ResumeExtractionSchema>;

export const InterviewQuestionsSchema = z.object({
  technical_questions: z.array(z.string()),
  behavioral_questions: z.array(z.string()),
  situational_questions: z.array(z.string()),
  candidate_specific_questions: z.array(z.string()),
  follow_up_questions: z.array(z.string()),
});
export type InterviewQuestionsResult = z.infer<typeof InterviewQuestionsSchema>;

// Feedback scores (technical_knowledge, etc.) and the interviewer's own
// recommendation are human input, never regenerated by AI — this schema is
// only the AI's read of what the human already submitted, for HR's benefit.
export const InterviewEvaluationSchema = z.object({
  summary: z.string(),
  strengths: z.array(z.string()),
  concerns: z.array(z.string()),
  technical_assessment: z.string(),
  communication_assessment: z.string(),
  role_fit_assessment: z.string(),
  suggested_next_action: z.string(),
});
export type InterviewEvaluationResult = z.infer<typeof InterviewEvaluationSchema>;
